const ADD_TO_FAVORITE="ADD_TO_FAVORITE";
const REMOVE_FROM_FAVORITE="REMOVE_FROM_FAVORITE";
const FETCH_FAVORITES="FETCH_FAVORITES";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_ERROR = "LOGIN_ERROR";
const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
const SIGN_UP_ERROR = "SIGN_UP_ERROR"

export {
    ADD_TO_FAVORITE,
    REMOVE_FROM_FAVORITE,
    LOGIN_SUCCESS,
    LOGIN_ERROR,
    SIGN_OUT_SUCCESS,
    SIGN_UP_SUCCESS,
    SIGN_UP_ERROR,
    FETCH_FAVORITES
}